from .base import ButtplugError as ButtplugError
from _typeshed import Incomplete

class ClientError(ButtplugError):
    message: Incomplete
    def __init__(self, message: str) -> None: ...

class ReconnectError(ClientError):
    def __init__(self, name: str) -> None: ...

class ScanNotRunningError(ClientError): ...
class UnsupportedCommandError(ClientError): ...
class UnexpectedMessageError(ClientError): ...
class ConnectorError(ClientError): ...

class InvalidAddressError(ConnectorError):
    def __init__(self, address: str) -> None: ...

class ServerNotFoundError(ConnectorError):
    def __init__(self, address: str) -> None: ...

class InvalidHandshakeError(ConnectorError): ...

class WebsocketTimeoutError(ConnectorError):
    def __init__(self, address: str) -> None: ...

class DisconnectedError(ConnectorError):
    def __init__(self, message: str) -> None: ...
