from .base import ButtplugError as ButtplugError
from _typeshed import Incomplete
from enum import IntEnum

class ServerError(ButtplugError):
    code: Incomplete
    message: Incomplete
    def __init__(self, code: int, message: str) -> None: ...

class UnknownServerError(ServerError): ...
class InitServerError(ServerError): ...
class PingServerError(ServerError): ...
class MessageServerError(ServerError): ...
class DeviceServerError(ServerError): ...

class ErrorCode(IntEnum):
    ERROR_UNKNOWN = 0
    ERROR_INIT = 1
    ERROR_PING = 2
    ERROR_MSG = 3
    ERROR_DEVICE = 4
    def exception(self, message: str) -> ServerError: ...
